
version: '2'
services:
  auctiondb:
    image: 'mongo:3'
    ports:
      - "27017:27017"
  server:
    build: .
    links:
      - "auctiondb"
    ports:
      - "1337:1337"
    command: bash -c "bash ./wait-for-it.sh auctiondb:27017 -t 300 && sails lift"
    depends_on:
      - auctiondb
    restart: always
